spring:
  application:
    name: axon-dashboard-jpa
  datasource:
    url: jdbc:postgres@postgres:postgresql://localhost:5432/axon_dashboard
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
